language: c
compiler: gcc
  - env
before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cmake check
  - export CC="gcc-4.8"
before_script:
  - mkdir build
  - cd build
  - cmake -D BUILD_TESTS:BOOL=TRUE ..
script:
  - make
  - ctest
branches:
  only:
    - master
